version: '3.3'
services:
# === Application flowerpower ===
  flowerpower:
    labels:
      - type=application
    ports:
        - '9081:9080'
    restart: always
    build:
      context: ./apps/flowerpower
    networks:
      - iot_dataset
    depends_on:
      - "mqtt_server"

# === Application smartkettle ===
  smartkettle:
    labels:
      - type=application
    ports:
        - '9082:9080'
    restart: always
    build:
      context: ./apps/smartkettle 
    networks:
      - iot_dataset
    depends_on:
      - "mqtt_server"

# === Application smarttv ===
  smarttv:
    labels:
      - type=application
    ports:
        - '9083:9080'
    restart: always
    build:
      context: ./apps/smarttv
    networks:
      - iot_dataset
    depends_on:
      - "mqtt_server"

# === Application windwow ===
  windwow:
    labels:
      - type=application
    ports:
        - '9084:9080'
    restart: always
    build:
      context: ./apps/windwow
    networks:
      - iot_dataset
    depends_on:
        - "mqtt_server"

# === Application smarteeth ===
  smarteeth:
    labels:
      - type=application
    ports:
        - '9085:9080'
    restart: always
    build:
      context: ./apps/smarteeth
    networks:
      - iot_dataset
    depends_on:
        - "mqtt_server"

# === Application smartoven ===
  smartoven:
    labels:
      - type=application
    ports:
        - '9086:5000'
    restart: always
    build:
      context: ./apps/smartoven
    networks:
      - iot_dataset
    depends_on:
        - "mqtt_server"

# === MQTT broker ===
  mqtt_server:
    labels:
      - type=infrastructure
    image: eclipse-mosquitto
    ports:
      - 9883:1883
      - 10001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    networks:
      - iot_dataset

# === The hub application ===
  hub_app:
    labels:
      - type=infrastructure
    privileged: true
    restart: always
    build:
      context: ./hub
    volumes:
      - ./hub/src:/project/src
      - ./hub/features:/project/features
    networks:
      - iot_dataset
    depends_on:
        - "mqtt_server"

volumes:
  mosquitto_data:
  mosquitto_logs:
      
networks:
  iot_dataset:
    external: true
